import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import oauthRouter from "./oauth";
import entriesRouter from "./entries";
import creditsRouter from "./credits";
import customersRouter from "./customers";
import reportsRouter from "./reports";
import backupRouter from "./backup";
import adminRouter from "./admin";
import closingRouter from "./closing";
import inventoryMastersRouter from "./inventory-masters";
import productsRouter from "./products";
import purchaseBillsRouter from "./purchase-bills";
import productSalesRouter from "./product-sales";
import companyReplacementsRouter from "./company-replacements";
import stockAdjustmentsRouter from "./stock-adjustments";
import supplierBalanceRouter from "./supplier-balance";
import billAttachmentsRouter from "./bill-attachments";
import permissionsRouter from "./permissions";
import pinSecurityRouter from "./pin-security";
import supplierDuesRouter from "./supplier-dues";
import warrantyCheckRouter from "./warranty-check";
import mobilePurchasesRouter from "./mobile-purchases";
import recycleBinRouter from "./recycle-bin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(oauthRouter);
router.use(entriesRouter);
router.use(creditsRouter);
router.use(customersRouter);
router.use(reportsRouter);
router.use(backupRouter);
router.use(adminRouter);
router.use(closingRouter);
router.use(inventoryMastersRouter);
router.use(productsRouter);
router.use(purchaseBillsRouter);
router.use(productSalesRouter);
router.use(companyReplacementsRouter);
router.use(stockAdjustmentsRouter);
router.use(supplierBalanceRouter);
router.use(billAttachmentsRouter);
router.use(permissionsRouter);
router.use(pinSecurityRouter);
router.use(supplierDuesRouter);
router.use(warrantyCheckRouter);
router.use(mobilePurchasesRouter);
router.use(recycleBinRouter);

export default router;
